[package]
name = "epoll"
version = "0.1.0"
authors = ["Gopa Kumar <gopakumarce@gmail.com>"]
edition = "2018"

[dependencies]
libc = { version = "0.2.171", features = [ "extra_traits" ] }
efd = { path = "../../unix/efd" }
